- name: Install Fedora packages
  become: yes
  become_method: sudo
  ansible.builtin.dnf:
    name:
    - git
    - git-filter-repo
    - ansible
    - fish
    - util-linux-user
    - neovim
    - gcc-c++
    - ripgrep
    - exa
    - tmux
    - jq
    - bat
    - tldr
    - python3-pip
    - pipx
    - python3-poetry
    - bpytop
    state: latest

- name: Install NvChad
  ansible.builtin.shell:
    cmd: "git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1"

- name: Install PDM
  ansible.builtin.shell:
    cmd: "curl -sSL https://raw.githubusercontent.com/pdm-project/pdm/main/install-pdm.py | python3 -"


