- name: Install Fedora packages
  become: True
  ansible.builtin.dnf:
    name:
    - git
    - git-filter-repo
    - ansible
    - python
    - fish
    - exa
    - tmux
    - jq
    - tldr
    - pipx
    - bat
    - neovim
    - bpytop
    - util-linux-user
    state: latest

