#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  vars:
    common_packaged_apps:
      - ansible
      - bat
      - bottom
      - fish
      - git
      - gitui
      - git-filter-repo
      - jq
      - lsd
      - neovim
      - pandoc
      - tmux
      - ripgrep
      - sd
      - tealdeer
      - uv # Python version and package manager
      - zoxide
    fedora_apps:
      - fd-find
      - emacs
      - util-linux-user
    brew_apps:
      - fd
      - emacs-plus@29
      - cmake
    brew_casks:
      - calibre
      - drawio
      - firefox
      - font-hack-nerd-font
      - inkscape
      - iterm2
      - onedrive
      - github
      - logseq
      - gimp
      - signal
      - wireshark
      - logi-options-plus
      - linearmouse
      - rectangle
      - kindle
      - the-unarchiver
      - krita
      - kicad
      - vial
      - visual-studio-code

  tasks:

    - name: Fedora tasks
      when: ansible_facts.distribution == "Fedora"
      ansible.builtin.include_tasks:
        file: "tasks/Fedora.yml"

    - name: WSL2 Fedora tasks
      when:
        - ansible_facts.distribution_file_variety is defined
        - ansible_facts.distribution_file_variety == "RedHat"
        - ansible_facts.distribution == "Generic" # Dunno why they used this
      ansible.builtin.include_tasks:
        file: "tasks/Fedora.yml"

    - name: MacOS tasks
      when: ansible_facts.distribution == "MacOSX"
      ansible.builtin.include_tasks:
        file: "tasks/MacOS.yml"

    - name: Configs for all unix-like OSs
      when: ansible_facts.distribution != "Windows"
      ansible.builtin.include_tasks:
        file: "tasks/Unix_likes.yml"
