#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  tasks:

    - name: Create config folders
      file:
        dest: "~/.config/{{ item }}/"
        state: directory
        recurse: true
      loop:
        - tmux
        - fish
        - nvim
        - git

    - name: Link Tmux settings
      file:
        dest: ~/.config/tmux/tmux.conf
        src: "{{ playbook_dir }}/tmux.conf"
        state: link
        force: true
          
    - name: Link Fish settings
      file:
        dest: ~/.config/fish/config.fish
        src: "{{ playbook_dir }}/config.fish"
        state: link
        force: true

    - name: Link Global Git Config settings
      file:
        dest: ~/.gitconfig
        src: "{{ playbook_dir }}/gitconfig"
        state: link
        force: true

    - name: Fedora tasks
      when: 
      - ansible_facts.os_family == "RedHat"
      - ansible_facts.distribution == "Fedora"
      include_tasks:
        file: "Fedora.yml"

    - name: Fedora WSL2 Tasks
      when: 
      - ansible_facts.distribution_file_variety is defined
      - ansible_facts.distribution_file_variety == "RedHat"
      - ansible_facts.distribution == "Generic" # Dunno why they used this
      include_tasks:
        file: "Fedora-WSL.yml"

    - name: MacOS tasks
      when: ansible_facts.os_family == "Darwin"
      include_tasks:
        file: "Darwin.yml"

    - name: Other stuff to change manually
      debug:
        msg:
          - "Other changes that either have to be done manually or I haven't been bothered to script:"
          - "Change the default shell to fish"
          - "Set the terminal app to open Tmux by default with `tmux new -A`"
          - 'Test italics are woring in console with `echo -e "\e[3mitalic?\e[23m"`'

