#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  vars:
    common_packaged_apps:
      - ansible
      - bat
      - glances
      - fish
      - git
      - gitui
      - git-filter-repo
      - jq
      - lsd
      - neovim
      - pandoc
        #      - pdm
        #      - pipx
        #      I want to swap to 'Rye'
      - python
      - tmux
      - ripgrep
      - tealdeer
      - zoxide
      - sd
    brew_apps:
      - emacs-plus@29
      - fd
      - cmake
      - fheroes2
    brew_casks:
      - 1password
      - calibre
      - drawio
      - firefox
      - font-hack-nerd-font
      - inkscape
      - iterm2
      - onedrive
      - github
      - logseq
      - gimp
      - signal
      - steam
      - heroic
      - wireshark
      - logi-options-plus
      - linearmouse
      - rectangle
      - kindle
      - the-unarchiver
      - krita
      - kicad
      - via
      - vial
      - visual-studio-code

    fedora_apps:
      - 1password
      - fd-find
      - emacs
      - util-linux-user

  vars_prompt:

    - name: update_install
      prompt: "Update & Install packages (requires -K flag)? [yes | no]"
      default: "no"
      private: false

    - name: global_git
      prompt: "Link global git settings with personal email address? [yes | no]"
      default: "no"

  tasks:

    - name: Fedora tasks
      when: ansible_facts.distribution == "Fedora"
      ansible.builtin.include_tasks:
        file: "tasks/Fedora.yml"

    - name: WSL2 Fedora tasks
      when:
        - ansible_facts.distribution_file_variety is defined
        - ansible_facts.distribution_file_variety == "RedHat"
        - ansible_facts.distribution == "Generic" # Dunno why they used this
      ansible.builtin.include_tasks:
        file: "tasks/Fedora.yml"

    - name: MacOS tasks
      when: ansible_facts.distribution == "MacOSX"
      ansible.builtin.include_tasks:
        file: "tasks/MacOS.yml"

    - name: Configs for all unix-like OSs
      when: ansible_facts.distribution != "Windows"
      ansible.builtin.include_tasks:
        file: "tasks/Unix_likes.yml"
