#!/usr/bin/env ansible-playbook

---
- name: Configure RHEL8 workstation
  hosts: 
    localhost:
      ansible_connection: local
      ansible_python_interpreter: auto

  tasks:

    - name: Map Tmux settings
      file:
        dest: ~/.tmux.conf
        src: ~/Repos/dotfiles/.tmux.conf
        state: link
          
    - name: Map Fish settings
      file:
        dest: ~/.config/fish
        src: ~/Repos/dotfiles/.config/fish
        state: link

    - name: Map Neovim settings
      file:
        dest: ~/.config/nvim
        src: ~/Repos/dotfiles/.config/nvim
        state: link
        force: True

    - name: Map Git Config settings
      file:
        dest: ~/.gitconfig
        src: ~/Repos/dotfiles/.gitconfig
        state: link
        force: True

