#!/usr/bin/env ansible-playbook

---
- name: Configure RHEL8 workstation
  hosts: localhost
  tasks:


    - name: Map Tmux settings
      file:
        dest: ~/.tmux.conf
        src: ~/Repos/dotfiles/.tmux.conf
        state: link
          
    - name: Map Fish settings
      file:
        dest: ~/.config/fish
        src: ~/Repos/dotfiles/.config/fish
        state: link

    - name: Map Neovim settings
      file:
        dest: ~/.config/nvim
        src: ~/Repos/dotfiles/.config/nvim
        state: link
        force: True


