#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  tasks:

    - name: Install packages
      become: true
      package:
        name:
        - ansible
        - tldr
        - tmux
        - fish
        - jq
        - exa
        - neovim
        state: latest

    - name: Update packages
      become: true
      package:
        state: latest

    - name: Set my default shell
      become: true
      user:
        name: luke
        shell: /bin/fish

    - name: Neovim directory
      file:
        dest: ~/.config/nvim
        state: directory
    
    - name: Map Neovim settings
      file:
        dest: ~/.config/nvim/init.vim
        src: ~/Repos/LukeDRussell/dotfiles/.config/nvim/init.vim
        state: link
    
    - name: Map Tmux settings
      file:
        dest: ~/.tmux.conf
        src: ~/Repos/LukeDRussell/dotfiles/.tmux.conf
        state: link
          
    - name: Map Fish settings
      file:
        dest: ~/.config/fish
        src: ~/Repos/LukeDRussell/dotfiles/.config/fish
        state: link

    - name: Map git settings
      file:
        dest: ~/.gitconfig
        src: ~/Repos/LukeDRussell/dotfiles/.gitconfig
        state: link

