#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  tasks:

    - name: Install packages
      become: true
      package:
        name:
        - ansible
        - tldr
        - tmux
        - fish
        - jq
        - exa
        - neovim
        - glances
        - make
        - gcc 
        - zlib-devel
        - bzip2
        - bzip2-devel 
        - readline-devel 
        - sqlite
        - sqlite-devel 
        - openssl-devel 
        - tk-devel 
        - libffi-devel
        - xz-devel
        state: latest

    - name: Update packages
      become: true
      package:
        state: latest

    - name: Set my default shell
      become: true
      user:
        name: luke
        shell: /bin/fish

    - name: Neovim directory
      file:
        dest: ~/.config/nvim
        state: directory
    
    - name: Map Neovim settings
      file:
        dest: ~/.config/nvim/init.vim
        src: ~/Repos/LukeDRussell/dotfiles/.config/nvim/init.vim
        state: link
    
    - name: Map Tmux settings
      file:
        dest: ~/.tmux.conf
        src: ~/Repos/LukeDRussell/dotfiles/.tmux.conf
        state: link
          
    - name: Map Fish settings
      file:
        dest: ~/.config/fish
        src: ~/Repos/LukeDRussell/dotfiles/.config/fish
        state: link

    - name: Map git settings
      file:
        dest: ~/.gitconfig
        src: ~/Repos/LukeDRussell/dotfiles/.gitconfig
        state: link

    - name: Install pipx
      pip: 
        name: pipx

    - name: Install Python Poetry
      command: pipx install poetry
    
    - name: Manual installs
      debug:
        msg:
          These commands need to be run manually:
          - 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
          - 'curl -L https://get.oh-my.fish | fish'
          - 'curl https://pyenv.run | bash'
          - 'pyenv update'
          - dnf copr enable dawid/better_fonts
          - dnf install fontconfig-enhanced-defaults fontconfig-font-replacements

