#!/usr/bin/env ansible-playbook

---
- name: Configure workstation
  hosts: localhost
  tasks:

    - name: Install packages
      become: true
      package:
        name:
        - ansible
        - tldr
        - tmux
        - fish
        - jq
        - exa
        state: latest

    - name: Update packages
      become: true
      package:
        state: latest

    - name: Set my default shell
      become: true
      user:
        name: luke
        shell: /bin/fish


    - name: Neovim dotfiles
      file:
        dest: ~/.config/nvim
        state: directory
    
    - name: Map Neovim settings
      file:
        dest: ~/.config/nvim/init.vim
        src: ~/Repos/LukeDRussell/dotfiles/.config/nvim/init.vim
        state: link
    
    - name: Install vim-plug
      command: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: Map Tmux settings
      file:
        dest: ~/.tmux.conf
        src: ~/Repos/LukeDRussell/dotfiles/.tmux.conf
        state: link
          
    - name: Map Fish settings
      file:
        dest: ~/.config/fish
        src: ~/Repos/LukeDRussell/dotfiles/.config/fish
        state: link

# Manual Steps
#    - name: Install Python Poetry
#      command: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
