- name: Install packages
  community.general.homebrew:
    name: "{{ common_packaged_apps + brew_apps }}"
    state: present

- name: Upgrade packages
  community.general.homebrew:
    upgrade_all: true

- name: Install casks
  community.general.homebrew_cask:
    name: "{{ brew_casks }}"
    state: present

- name: Upgrade casks
  community.general.homebrew_cask:
    upgrade_all: true

- name: Turn off MacOS defaults (booleans)
  community.general.osx_defaults:
    key: "{{ item }}"
    type: bool
    value: false
  loop:
    - ApplePressAndHoldEnabled
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticCapitalizationEnabled
    - NSAutomaticQuoteSubstitutionEnabled
    - NSAutomaticSpellingCorrectionEnabled
    - QuitMenuItem

- name: Change default shell
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    shell: "/opt/homebrew/bin/fish"
