- name: Install packages
  community.general.homebrew:
    update_homebrew: true
    name: "{{ common_packaged_apps + brew_apps + brew_casks }}"
    state: present

- name: Install MacOS apps
  ansible.builtin.package:
    name: macos_apps
    state: present

- name: Remove press and hold on keyboard
  community.general.osx_defaults:
    key: ApplePressAndHoldEnabled
    type: bool
    value: false
  loop:
    - NSAutomaticDashSubstitutionEnabled
    - NSAutomaticCapitalizationEnabled
    - NSAutomaticQuoteSubstitutionEnabled
    - NSAutomaticSpellingCorrectionEnabled
    - QuitMenuItem

- name: Change default shell
  ansible.builtin.user:
    user: "{{ ansible_user_id }}"
    shell: "/opt/homebrew/bin/fish"
